bloomberg/attrs-strict

- .travis.yml
Signed-off-by: Erik <eseulean@bloomberg.net>
Add support for TravisCI
> Add TravicCI .yml file

- tox.ini
Also move to token user name; per https://pypi.org/help/#apitoken.
> Add verbose flag to twine and make it token based

- README.md
- setup.cfg
- setup.py
Signed-off-by: Erik <eseulean@bloomberg.net>
*Issue number of the reported bug or feature request: #<number>*
- Adds badges
- Update setup.py for friendlier `pypi` page.
> Add details for pypi page

- README.md
- doc/index.rst
*Issue number of the reported bug or feature request: #<number>*
Improve examples in the documentation to reflect the changes done in the way the errors are being represented.
> Update examples in the documentation

- .readthedocs.yml
> configure readthedocs

- attrs_strict/_error.py
- attrs_strict/_type_validation.py
- tests/test_container.py
Signed-off-by: UENO Satosi <satoshi-ueno@iij.ad.jp>
*Issue number of the reported bug or feature request: #20 *
Added custom empty error class and raise it instead of ValueError.
**Testing performed**
Tested with sample code on #20.
> Add attribute name to empty error message (#20)

- .travis.yml
- setup.py
- tox.ini
> Add support for python3.8

- attrs_strict/_type_validation.py
- tests/test_tuple.py
> Add support for variable length tuples in Tuple type_validator

- README.md
- attrs_strict/__init__.py
- attrs_strict/_error.py
- attrs_strict/_type_validation.py
- tests/test_callable.py
- tests/test_newtype.py
*Issue number of the reported bug or feature request: #18*
Updated Readme, added support for `Callable` types and added tests for the same
**Testing performed**
Unit tested
**Additional context**
Did it during the Guild Week
> Support callables

- .github/workflows/check.yml
- .github/workflows/publish.yaml
- tox.ini
It's faster and better integrated with Github. 
TODO: check how to migrate the deploy phase.
> Move to Github Actions from Travis

- .github/workflows/check.yml
- .github/workflows/publish.yaml
- tox.ini
> Fix Github Actions

- .github/workflows/check.yml
- tox.ini
> Python 3.9 support

- README.md
> Add python implementations supported to README

- .github/workflows/check.yml
- tox.ini
> Move to Python 3.9 final and build over pep517

- .pre-commit-config.yaml
- pyproject.toml
- setup.cfg
- src/attrs_strict/_type_validation.py
- tox.ini
- Bump mypy
- Add context report for coverage.py
Signed-off-by: Bernát Gábor <bgabor8@bloomberg.net>
> Format tox.ini

- README.md
Signed-off-by: Bernát Gábor <bgabor8@bloomberg.net>
> Wrap readme at 80 character too

- .pre-commit-config.yaml
- setup.cfg
- src/attrs_strict/__init__.pyi
- src/attrs_strict/_error.pyi
- src/attrs_strict/_type_validation.pyi
- tests/test_container.py
Signed-off-by: Bernát Gábor <bgabor8@bloomberg.net>
> Fix the CI and bump linters

- .pre-commit-config.yaml
- setup.cfg
- src/attrs_strict/_type_validation.py
- tox.ini
- whitelist.txt
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>
> Bump linters

- .pre-commit-config.yaml
- pyproject.toml
- setup.cfg
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>
> Bump dependencies

- .github/workflows/check.yml
- tox.ini
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>
> Check 3.11 support

- .github/workflows/check.yml
- .pre-commit-config.yaml
- pyproject.toml
- setup.cfg
- tox.ini
> Bump to 3.11

- .readthedocs.yml
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>
> Simplify docs

- .pre-commit-config.yaml
- pyproject.toml
- setup.cfg
- tests/test_callable__py3.py
- tests/test_list.py
- tests/test_union.py
- tox.ini
Committed via https://github.com/asottile/all-repos
> Bump deps and tools
